### ISSUE TITLE
Come up with strategies for retrying failed work.

### ISSUE THREAD

**Issue by ctrlplusb** [ctrlplusb/react-jobs#11]
I'll plant ideas as they arrive.

**Comment by ctrlplusb** [comment]
__Idea number 1__

Add an additional property to the `withJobs` options object.

```js
withJob(() => 'foo', { retryCount: 3 })
```

**Comment by ctrlplusb** [comment]
@smirea - thoughts here?

This case can't be covered by the new `shouldWorkAgain` config item, as the error could occur on first run (mount).  Perhaps having a simply `retryCount` is best?

The retry count would then also be valid for when work is run again due to `shouldWorkAgain`

**Comment by smirea** [comment]
i was thinking about this as well. Do you think retrying should be part of this library?
There are definitely a bunch of features react-jobs could support, but this is also another thing that's not complicated for an user to implement by themselves that's tailor to their exact implementation:

- timeout between retries? 
- progressive fall-back? 
- only retry for specific errors? (no point retrying for 404s, but maybe for some 500s)

We could guess what would be a good balance between MVP and what to support, my thoughts on this more go along the lines of show examples in the README on how achieve this instead of baking it in

**Comment by ctrlplusb** [comment]
Bang on again!

https://github.com/sindresorhus/p-retry 👈 👍

**Comment by ctrlplusb** [comment]
Added example. :)
